DROP DATABASE KOMMUNITYON;
CREATE DATABASE KOMMUNITYON;
USE KOMMUNITYON;

SELECT E.*, U.NOME FROM ENDERECO E INNER JOIN USUARIO U ON E.ID_USUARIO = U.ID;
SELECT * FROM SOLICITACAO ORDER BY DATA_ABERTURA;
 SELECT * FROM USUARIO_LIKE_SOLICITACAO;
 SELECT * FROM USUARIO;
 SELECT * FROM TAG;
SELECT * FROM SOLICITACAO_TAG;
SELECT * FROM SOLICITACAO S INNER JOIN SOLICITACAO_TAG ST ON ST.ID_SOLICITACAO = S.ID WHERE ST.ID_TAG = 1;
SELECT DISTINCT * FROM SOLICITACAO S WHERE S.ID NOT IN (SELECT ID_SOLICITACAO FROM SOLICITACAO_TAG);
SELECT * FROM SOLICITACAO S WHERE S.ID = 2;
 
 SELECT s.id FROM Solicitacao s WHERE s.data_conclusao IS NULL AND s.id_usuario = 2;

CREATE TABLE USUARIO(
ID BIGINT AUTO_INCREMENT PRIMARY KEY,
NOME VARCHAR(80) NOT NULL,
CPF VARCHAR(15) NOT NULL UNIQUE,
EMAIL VARCHAR(70) NOT NULL UNIQUE,
SENHA VARCHAR(30) NOT NULL,
TELEFONE VARCHAR(22) NOT NULL,
DATA_INTERACAO_1 TIMESTAMP,
DATA_INTERACAO_2 TIMESTAMP,
TIPO VARCHAR(3) DEFAULT 'USU',
FOTO_PERFIL MEDIUMBLOB
);

INSERT INTO USUARIO VALUES 
(0, "Administrador", "11111111111", "administrador.kon@gmail.com", "@@Kon!2025", "1", null, null, "ADM", null);

INSERT INTO USUARIO(NOME, CPF, EMAIL, SENHA, TELEFONE, TIPO)
VALUES("JOÃO PEDRO", "40172440840", "JOAOPEDROOLISAVIOLI@GMAIL.COM", "123", "11978521152", "USU");

INSERT INTO USUARIO(NOME, CPF, EMAIL, SENHA, TELEFONE)
VALUES("Daniel Cravo", "40172440841", "danielcravo@gmail.com", "12345", "11978521152");

CREATE TABLE ENDERECO(
ID BIGINT AUTO_INCREMENT PRIMARY KEY,
ID_USUARIO BIGINT,
UF VARCHAR(2) NOT NULL,
BAIRRO VARCHAR(60) NOT NULL,
CIDADE VARCHAR(30) NOT NULL,

FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO(ID) ON DELETE CASCADE
);

CREATE TABLE SOLICITACAO(
ID BIGINT AUTO_INCREMENT PRIMARY KEY,
ID_USUARIO BIGINT,
TITULO VARCHAR(60) NOT NULL,
BAIRRO VARCHAR(60) NOT NULL,
DESCRICAO VARCHAR(450) NOT NULL,
NUM_LIKES INT DEFAULT 0,
NUM_COMENTARIOS INT DEFAULT 0,
DATA_ABERTURA TIMESTAMP DEFAULT NOW(),
DATA_CONCLUSAO DATETIME,
ANONIMO ENUM('0', '1') DEFAULT '0',

FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO(ID) ON DELETE CASCADE
);

INSERT INTO SOLICITACAO(ID_USUARIO, TITULO, BAIRRO, DESCRICAO, NUM_LIKES, DATA_ABERTURA) 
VALUES(1, "SEMÁFORO QUEBRADO", "JD. AEROPORTO", "O SEMÁFORO TAL TA QUEBRADO HÁ 3 SEMANAS CAUSANDO TRANSITO NO LOCAL",
5, NOW());

INSERT INTO SOLICITACAO(ID_USUARIO, TITULO, BAIRRO, DESCRICAO, NUM_LIKES, DATA_ABERTURA) 
VALUES(1, "LOMBADA", "JD. AEROPORTO", "PRECISA DE LOMBADA NA RUA TAL",
3, NOW());

INSERT INTO SOLICITACAO(ID_USUARIO, TITULO, BAIRRO, DESCRICAO, NUM_LIKES, DATA_ABERTURA) 
VALUES(1, "BLABLA", "BLABLA", "BLABLABLABLA",
13, NOW());

CREATE TABLE USUARIO_LIKE_SOLICITACAO(
ID BIGINT PRIMARY KEY AUTO_INCREMENT,
ID_USUARIO BIGINT,
ID_SOLICITACAO BIGINT,

FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO(ID),
FOREIGN KEY (ID_SOLICITACAO) REFERENCES SOLICITACAO(ID)
);

CREATE TABLE COMENTARIO(
ID BIGINT PRIMARY KEY AUTO_INCREMENT,
ID_USUARIO BIGINT,
ID_SOLICITACAO BIGINT,
TEXTO VARCHAR(255),

FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO (ID) ON DELETE CASCADE,
FOREIGN KEY (ID_SOLICITACAO) REFERENCES SOLICITACAO (ID) ON DELETE CASCADE
);

CREATE TABLE TAG(
ID BIGINT PRIMARY KEY AUTO_INCREMENT,
NOME VARCHAR(30) NOT NULL
);

INSERT INTO TAG (NOME) VALUES ("Trânsito");
INSERT INTO TAG (NOME) VALUES ("Saúde");
INSERT INTO TAG (NOME) VALUES ("Avenida");
INSERT INTO TAG (NOME) VALUES ("Energia");
INSERT INTO TAG (NOME) VALUES ("Inclusão");
INSERT INTO TAG (NOME) VALUES ("Violência");
INSERT INTO TAG (NOME) VALUES ("Entretenimento");
INSERT INTO TAG (NOME) VALUES ("Serviços públicos");

CREATE TABLE SOLICITACAO_TAG(
ID_SOLICITACAO BIGINT,
ID_TAG BIGINT,

FOREIGN KEY (ID_SOLICITACAO) REFERENCES SOLICITACAO(ID) ON DELETE CASCADE,
FOREIGN KEY (ID_TAG) REFERENCES TAG(ID) ON DELETE CASCADE,
PRIMARY KEY (ID_SOLICITACAO, ID_TAG)
);

CREATE TABLE CODIGO_RECUPERACAO(
ID BIGINT AUTO_INCREMENT PRIMARY KEY,
CODIGO VARCHAR(6) NOT NULL UNIQUE,
ID_USUARIO BIGINT NOT NULL,

FOREIGN KEY(ID_USUARIO) REFERENCES USUARIO(ID)
);